### ISSUE TITLE
Using Euler angles to produce misorientation quaternion as input to GBfive2oct.m

### ISSUE THREAD

**Issue by sgbaird** [ichesser/GB_octonion_code#1]
Hi Ian (and Toby),

I've been continuing working in the octonion framework and ran into an issue with Euler angles. It's likely a lack of understanding on my part, but I'm a bit confused by a certain result. When I use eu2qu.m with Bunge Euler angles, I get different octonions and different minimum arc lengths based on which convention I use for epsijk (per the paper [here](https://dx.doi.org/10.1088/0965-0393/23/8/083501)).

For example:
```
Morawiec convention
o1: 0.8275 0.4719 -0.2832 0.1113 0.8108 0.2004 -0.5499 0
o2: 0.2105 0.9672 -0.1420 -0.0087 0.4972 0.7543 0.4288 0
omega = 0.28327

Alternative
o1: 0.3414 0.4891 -0.8004 -0.0604 0.5487 0.6593 -0.5141 0
o2: 0.6300 0.5422 -0.4604 -0.3119 0.7371 -0.0039 -0.6758 0
omega = 0.63176
```

(produced via a short MATLAB script I wrote: [setGlobal_epsijk_oct_test.txt](https://github.com/ichesser/GB_octonion_code/files/5093631/setGlobal_epsijk_oct_test.txt), just rename extension to ".m" since I couldn't upload a .m file).

I was under the impression that epsijk wouldn't matter since it only factors into eu2qu.m (as far as I can tell) in the workflow of converting from 5DOF to octonion representations. Do you have some clarification for this?

Sterling

Update: (from email correspondence) I think I can stick with epsijk = 1 since this gave the same misFZ quaternion before and after adding setGlobal_epsijk to qmult.m. Thank you for the suggestions via email.

**Comment by ichesser** [comment]
From offline correspondence about this issue: 

Ian: I suspect that line 51 where you compute qm is the culprit and that you are actually producing different misorientations (in the misorientation fundamental zone) with different choice of epsijk. 
Looking at the rotation conversion paper you mention, Eqn 24 gives a formula for quaternion multiplication that explicitly contains P = +1/-1. I believe this needs to be implemented into the qmult function to account for the P = -1 case. 

Sterling: Adding epsijk to qmult.m fixed the misorientation issue, and to get consistent output from GBoct2five.m it looks likes I'd still have to figure out something with either qinv.m or L_p(r) (eqns 8 & 9), since L_p(r) explicitly contains P = +1/-1 as well (eqn 24). My first attempt at adjusting this part didn't work, but for now, I'm think I can stick with P = 1 since this gave the same misFZ quaternion before and after changing qmult.m.
