### ISSUE TITLE
Quaternion Inverse Convention

### ISSUE THREAD

**Issue by sgbaird** [ichesser/GB_octonion_code#3]
Is there a particular reason the convention used here is that qm = qmult(qB,qinv(qA)) as opposed to qm = qmult(qinv(qA),qB)?

**Comment by ichesser** [comment]
Hi Spencer, 

The motivation for this convention is that it represents the sequence of operations to rotate qA to qB. Consider how the composition qB qinv(qA) acts on grain orientation qA. First, qA is sent to a reference orientation (the identity) and then the second rotation qB is applied to obtain the orientation of grain B. 

I will respond to your other questions tomorrow -- so that I can help out as well as I can, what are your goals for using this codebase? 

--
Ian Chesser / ichesser@andrew.cmu.edu / 713-516-2491

**Comment by sgbaird** [comment]
Hi Ian,

Ok, thanks for the response! In our group (@oliverkjohnson), we use the latter definition which has caused conflicts with interfacing some of our code with the GB octonion code. Both conventions produce the same misorientation angle but different axes of rotations, so I thought I'd ask. Is this convention something used primarily in this paper or also across the De Graef & Holm groups?

We're interested in doing grain boundary property interpolation, and the octonion framework seems well-suited to that. I've implemented vectorization and parallelization on various functions in this repository, so speed hasn't been as much of an issue with the MATLAB versions, but some of the results have been strange (see Dr. Johnson's email thread, subject: _Octonion Distance for [100] tilts_ and GitHub issue [Troubleshooting 5DOF ↔️ octonion conversions](https://github.com/ichesser/GB_octonion_code/issues/2#issue-706003490)). I've primarily been using _GBfive2oct.m_ rather than _GBmat2oct.m_ which could be part of the issue.

Let me know if you have other questions. Thank you!

Sterling

**Comment by ichesser** [comment]
Hi Sterling, 

I would suggest working with GBmat2oct.m rather than GBfive2oct.m. I have primarily used this code starting with GBs defined by orientation matrices (as in the Example0_conversion_to_octonion.m file, example 3) and will be able to provide quicker help here. I haven't yet figured out what is going on with the issues with GBfive2oct in Oliver's email and your other post.

That is nice to hear that you have improved some of these functions. The misorientation convention is just for this paper and I am not aware of fixed group-wide conventions. 

--
Ian Chesser / ichesser@andrew.cmu.edu / 713-516-2491

**Comment by sgbaird** [comment]
Hi Ian @ichesser,

Thanks for the response! Per your suggestion, I started working with GBmat2oct.m. It seems to be producing the expected octonion distances which is nice. Do you know how to do the reverse conversion (i.e. GBoct2mat)?

Sterling

**Comment by ichesser** [comment]
Hey Sterling, 

Glad GBmat2oct is behaving as expected. You are correct that GBoct2mat has not been implemented -- it should be relatively straightforward to reverse engineer. I have a busy month but do eventually plan to return to this codebase to make some improvements. 

Best, 
--
Ian Chesser / ichesser@andrew.cmu.edu / 713-516-2491
